### ISSUE TITLE
ApiGen 5.x

### ISSUE THREAD

**Issue by splitbrain** [varunsridharan/action-apigen#2]
From what I understand, ApiGen 4 is no longer supported and has been superseded by the 5.x version. Is there any chance you could upgrade this action to make use of the 5.x version? I'm running into problems with bugs that have been fixed by the ApiGen people but seem to only be available in 5.x.

**Comment by varunsridharan** [comment]
@splitbrain 

Thanks for giving this a try. 

Well i tried to use the very latest version of APIGEN but i kept getting ton of errors while making it run. and it seems that APIGEN is dead and the last release was 4.x 

but i did tried using the branch source code but nothing works.

**Comment by splitbrain** [comment]
I see. I've read a bit more into it and it seems the dev hit a road block with used library and burned out on it :disappointed: Seems like phpdocumentor is the only project at least somewhat alive.

thanks for this action anyway
